version: '3.3'

services:
  l4d4_nuxt:
    build: .
    container_name: l4d4_nuxt
    restart: always
    expose:
      - 3000
    networks:
      - default

networks:
  default:
    external: true
    name: evilcorp
